name: WebdriverIO Tests and Allure Report Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run WebdriverIO tests in Chrome (Headless)
        run: |
          # Set the DISPLAY environment variable for headless Chrome
          export DISPLAY=:99
          Xvfb :99 -ac &
          # Run tests
          npm run wdio
          
      - name: Generate Allure report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t webdriverio-tests .

      - name: Run WebdriverIO tests in Docker and store container ID
        id: run-docker
        run: |
          CONTAINER_ID=$(docker run -d webdriverio-tests)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          docker wait $CONTAINER_ID || true

      - name: Verify Allure report exists
        run: |
          docker exec ${{ env.CONTAINER_ID }} ls -l /usr/src/app/allure-report || true

      - name: Copy Allure report from Docker
        run: |
          docker cp ${{ env.CONTAINER_ID }}:/usr/src/app/allure-report ./allure-report || true