name: WebdriverIO Test and Deploy

on:
  push:
    branches:
      - main  # Change to your main branch if necessary
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (LTS version 20.13.1)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.13.1'

    # Step 4: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Run WebdriverIO tests in headless mode
    - name: Run WebdriverIO tests
      run: npx run wdio

    # Step 6: Upload test results (Allure reports)
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: ./allure-results

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy Allure report to GitHub Pages
    - name: Deploy Allure report to GitHub Pages
      if: success()
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git clone --branch=gh-pages https://github.com/${{ github.repository }}.git gh-pages
        cp -R allure-report/* gh-pages/
        cd gh-pages
        git add .
        git commit -m "Deploy Allure report"
        git push https://github.com/${{ github.repository }}.git gh-pages