name: WebdriverIO Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run WebdriverIO tests in Chrome (Headless)
        run: |
          # Set the DISPLAY environment variable for headless Chrome
          export DISPLAY=:99
          Xvfb :99 -ac &
          # Run tests
          npm run wdio
          
      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report